#start grid: at the root; run (docker-compose -f src/main/resources/docker-compose.yml up --scale chrome=2 --remove-orphans -d)
#run test: at the root; run (mvn test -DexecutionAddress="localhost:4444" -DtargetOperatingSystem="Linux-64" -DmaximumPerformanceMode="2")
#end grid: at the root; run (docker-compose -f src/main/resources/docker-compose.yml down --remove-orphans)
#open the following url to monitor: http://localhost:4444/grid/console

version: '3.7'
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    ports:
      - 4444:4444
    environment:
      GRID_MAX_SESSION: 5
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIMEOUT: 300

  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - selenium-hub
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: 4444
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
      # set false for headless execution
      START_XVFB: "false"
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1